// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByKqC8VGc6T2-_gEDF1vzK-FzOIBsqOvk',
    appId: '1:912435335334:web:e9865576c0cdd521462467',
    messagingSenderId: '912435335334',
    projectId: 'stand-up-a955f',
    authDomain: 'stand-up-a955f.firebaseapp.com',
    storageBucket: 'stand-up-a955f.appspot.com',
    measurementId: 'G-S9LSMKML2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfGmHA40bzqPULpEIEyRWz-UfXf4hTWUs',
    appId: '1:912435335334:android:ccc64cab76e72a53462467',
    messagingSenderId: '912435335334',
    projectId: 'stand-up-a955f',
    storageBucket: 'stand-up-a955f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEK8UFD4i3wgbbx7MnjIPJN_bErLNwfzU',
    appId: '1:912435335334:ios:51bbc5ff172e5e63462467',
    messagingSenderId: '912435335334',
    projectId: 'stand-up-a955f',
    storageBucket: 'stand-up-a955f.appspot.com',
    iosClientId: '912435335334-g6bjcfgccmg774ik8h0kdg5a0rvp6tgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.standUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEK8UFD4i3wgbbx7MnjIPJN_bErLNwfzU',
    appId: '1:912435335334:ios:51bbc5ff172e5e63462467',
    messagingSenderId: '912435335334',
    projectId: 'stand-up-a955f',
    storageBucket: 'stand-up-a955f.appspot.com',
    iosClientId: '912435335334-g6bjcfgccmg774ik8h0kdg5a0rvp6tgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.standUp',
  );
}
